name: Publish to PyPI.org
on:
  release:
    types: [published]
# .github/workflows/ci-cd.yml
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/qcentroid-runtime-qiskit
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Check out the action locally
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install the packaging-related tools
      run: python3 -m pip install build twine poetry
    - name: build project
      run: python3 -m poetry build
    - name: check package
      run: python3 -m twine check dist/*
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
